export const destinations = [
  { name: "Andaman Islands", country: "India" },
  { name: "Goa", country: "India" },
  { name: "Kerala", country: "India" },
  { name: "Rajasthan", country: "India" },
  { name: "Kashmir", country: "India" },
  { name: "Ladakh", country: "India" },
  { name: "Himachal Pradesh", country: "India" },
  { name: "Uttarakhand", country: "India" },
  { name: "Sikkim", country: "India" },
  { name: "Assam", country: "India" },
  { name: "Karnataka", country: "India" },
  { name: "Tamil Nadu", country: "India" },
  { name: "West Bengal", country: "India" },
  { name: "Maharashtra", country: "India" },
  { name: "Gujarat", country: "India" },
  { name: "Odisha", country: "India" },
  { name: "Dubai", country: "United Arab Emirates" },
  { name: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "Singapore", country: "Singapore" },
  { name: "Bali", country: "Indonesia" },
  { name: "Thailand", country: "Thailand" },
  { name: "Maldives", country: "Maldives" },
  { name: "Sri Lanka", country: "Sri Lanka" },
  { name: "Nepal", country: "Nepal" },
  { name: "Vietnam", country: "Vietnam" },
  { name: "Malaysia", country: "Malaysia" },
  { name: "Hong Kong", country: "Hong Kong" },
  { name: "Japan", country: "Japan" },
  { name: "Switzerland", country: "Switzerland" },
  { name: "Italy", country: "Italy" },
  { name: "France", country: "France" },
  { name: "United Kingdom", country: "United Kingdom" },
  { name: "United States", country: "United States" },
  { name: "Australia", country: "Australia" },
];
