const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "aasvana";

export const brand = {
    name: APP_NAME,
    shortName: "Xm",
    author: 'Aquib Shahbaz',
    authorUrl: "https://www.justaquib.com",
    description: `${APP_NAME} is a powerful and flexible web application template designed for building modern, responsive, and user-friendly applications. It provides a clean and intuitive interface, along with a wide range of components and features to help developers create stunning applications quickly and efficiently.`,
    shortDescription: `${APP_NAME} is a powerful and flexible web application template designed for building modern, responsive, and user-friendly applications.`,
    tagline: `${APP_NAME} is a powerful and flexible web application template designed for building modern, responsive, and user-friendly applications.`,
    taglineDescription: `${APP_NAME} is a powerful and flexible web application template designed for building modern, responsive, and user-friendly applications.`,
    keywords: [
        "web application template",
        "responsive design",
        "user-friendly interface",
        "modern web applications",
        "flexible components",
        "intuitive navigation",
        "customizable themes",
        "cross-browser compatibility",
        "mobile-first design",
        "performance optimization",
        "accessibility features",
        "SEO-friendly",
        "developer-friendly",
        "open-source",
        "community support",
    ],
    travelName: "Aasvana",
    travelDescription: "Aasvana is a travel and booking platform designed to craft memorable journeys for every traveler, from island getaways to city tours.",
    url: "https://www.aasvana.com",
    logo: {
        light: "/images/logo-light.svg",
        dark: "/images/logo-dark.svg",
    },
    favicon: {
        light: "/images/favicon-light.svg",
        dark: "/images/favicon-dark.svg",
    },
    themeColor: "#ffffff",
    appleTouchIcon: {
        light: "/images/apple-touch-icon-light.png",
        dark: "/images/apple-touch-icon-dark.png",
    },
    travelKeywords: [
        "vacation rental",
        "Maui",
        "Hawaii",
        "beach vacation",
        "island vacation",
        "family vacation",
        "romantic getaway",
        "luxury vacation",
        "adventure vacation",
        "tropical vacation",
        "ocean view",
        "beachfront property",
        "pool",
        "hot tub",
        "outdoor activities",
        "water sports",
        "snorkeling",
        "surfing",
        "hiking",
        "golf",
        "shopping",
        "dining",
        "nightlife",
        "spa",
        "wellness",
        "relaxation",
        "family-friendly",
        "pet-friendly",
        "luxury amenities",
        "affordable rates",
        "special offers",
        "last-minute deals",
        "customer service",
        "guest reviews",
        "local attractions",
        "island tours",
        "cultural experiences",
        "sustainable tourism",
        "eco-friendly",
        "responsible travel",
        "travel tips",
        "travel guides",
        "travel blog",
        "travel photography",
        "travel inspiration",
        "travel planning",
        "travel advice",
        "travel resources",
    ],
    social: {
        facebook: "https://www.facebook.com/aasvana",
        twitter: "https://twitter.com/aasvana",
        instagram: "https://www.instagram.com/aasvana",
        linkedin: "https://www.linkedin.com/company/aasvana",
        youtube: "https://www.youtube.com/channel/aasvana",
        tiktok: "https://www.tiktok.com/@aasvana",
        pinterest: "https://www.pinterest.com/aasvana",
        reddit: "https://www.reddit.com/user/aasvana",
    },
    contact: {
        mobile: "+91 90000 00000",
        email:  "admin@aasvana.com",
        address: "Aasvana HQ",
        hours: "Mon-Fri 9am-5pm, Sat-Sun 10am-4pm",
    },
}