export const brand = {
    name: "Island Beach Vacation",
    shortName: "IBV",
    description: "Island Beach Vacation is a vacation rental company that offers a variety of properties for rent on the beautiful island of Maui, Hawaii. Our mission is to provide our guests with a memorable and enjoyable vacation experience.",
    url: "https://www.islandbeachvacation.com",
    logo: {
        light: "/images/logo-light.svg",
        dark: "/images/logo-dark.svg",
    },
    favicon: {
        light: "/images/favicon-light.svg",
        dark: "/images/favicon-dark.svg",
    },
    themeColor: "#ffffff",
    appleTouchIcon: {
        light: "/images/apple-touch-icon-light.png",
        dark: "/images/apple-touch-icon-dark.png",
    },
    keywords: [
        "vacation rental",
        "Maui",
        "Hawaii",
        "beach vacation",
        "island vacation",
        "family vacation",
        "romantic getaway",
        "luxury vacation",
        "adventure vacation",
        "tropical vacation",
        "ocean view",
        "beachfront property",
        "pool",
        "hot tub",
        "outdoor activities",
        "water sports",
        "snorkeling",
        "surfing",
        "hiking",
        "golf",
        "shopping",
        "dining",
        "nightlife",
        "spa",
        "wellness",
        "relaxation",
        "family-friendly",
        "pet-friendly",
        "luxury amenities",
        "affordable rates",
        "special offers",
        "last-minute deals",
        "customer service",
        "guest reviews",
        "local attractions",
        "island tours",
        "cultural experiences",
        "sustainable tourism",
        "eco-friendly",
        "responsible travel",
        "travel tips",
        "travel guides",
        "travel blog",
        "travel photography",
        "travel inspiration",
        "travel planning",
        "travel advice",
        "travel resources",
    ],
    social: {
        facebook: "https://www.facebook.com/islandbeachvacation",
        twitter: "https://twitter.com/islandbeachvacation",
        instagram: "https://www.instagram.com/islandbeachvacation",
        linkedin: "https://www.linkedin.com/company/islandbeachvacation",
        youtube: "https://www.youtube.com/channel/islandbeachvacation",
        tiktok: "https://www.tiktok.com/@islandbeachvacation",
        pinterest: "https://www.pinterest.com/islandbeachvacation",
        reddit: "https://www.reddit.com/user/islandbeachvacation",
    },
    contact: {
        mobile: "+1 (808) 555-1234",
        email:  "admin@islandbeachvacation.com",
        address: "123 Island Beach Rd, Maui, HI 96753",
        hours: "Mon-Fri 9am-5pm, Sat-Sun 10am-4pm",
    },
}